# Generated by Django 3.1.3 on 2020-11-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladmin.addclass')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('am_or_pm', models.CharField(max_length=50)),
                ('present_or_absent', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.students')),
            ],
            options={
                'db_table': 'student_attendance',
            },
        ),
    ]
