# Generated by Django 3.1.3 on 2020-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(upload_to='Students/'),
        ),
    ]
