# Generated by Django 3.1.3 on 2020-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201204_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_name',
            field=models.CharField(default='class_name', max_length=50),
        ),
    ]
