# Generated by Django 3.1.3 on 2020-12-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201206_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
