# Generated by Django 3.1.3 on 2020-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20201206_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
