# Generated by Django 3.1.3 on 2020-11-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'class_details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('employee_image', models.ImageField(upload_to='')),
                ('mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Employee_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('am_or_pm', models.CharField(max_length=10)),
                ('present_or_absent', models.CharField(max_length=20)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladmin.employee')),
            ],
            options={
                'db_table': 'employee_attendance',
            },
        ),
    ]
