# Generated by Django 3.1.3 on 2020-12-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
