# Generated by Django 3.1.3 on 2020-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0002_auto_20201204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(upload_to='Employees'),
        ),
    ]
