# Generated by Django 3.1.3 on 2020-12-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0003_auto_20201204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(max_length=100),
        ),
    ]
